# Generated by Django 4.2.30 on 2026-04-08 08:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kiraci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('yetkili_kisi', models.CharField(blank=True, max_length=150, verbose_name='Yetkili Kişi')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('kira_baslangic_tarihi', models.DateField(verbose_name='Kira Başlangıç Tarihi')),
                ('kira_bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Kira Bitiş Tarihi')),
                ('aylik_kira_tutari', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Aylık Kira Tutarı (₺)')),
                ('sozlesme', models.FileField(blank=True, null=True, upload_to='sozlesmeler/', verbose_name='Sözleşme Dosyası')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif Kiracı')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kiracı',
                'verbose_name_plural': 'Kiracılar',
                'ordering': ['firma_adi'],
            },
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField(verbose_name='Yıl')),
                ('ay', models.IntegerField(verbose_name='Ay')),
                ('odenen_tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ödenen Tutar (₺)')),
                ('odeme_turu', models.CharField(choices=[('resmi', 'Resmi (Banka/Havale)'), ('gayri_resmi', 'Gayri Resmi (Belgesiz)'), ('elden', 'Elden (Nakit)')], max_length=20, verbose_name='Ödeme Türü')),
                ('odeme_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Ödeme Tarihi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kiraci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='kiraci.kiraci', verbose_name='Kiracı')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-yil', '-ay'],
                'unique_together': {('kiraci', 'yil', 'ay')},
            },
        ),
    ]
