# Generated by Django 4.2.30 on 2026-04-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiraci', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odeme',
            options={'ordering': ['-yil', '-ay', '-olusturulma_tarihi'], 'verbose_name': 'Ödeme', 'verbose_name_plural': 'Ödemeler'},
        ),
        migrations.AlterUniqueTogether(
            name='odeme',
            unique_together=set(),
        ),
    ]
