# Generated by Django 4.2.30 on 2026-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiraci', '0002_alter_odeme_options_alter_odeme_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiraci',
            name='depozit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Depozit (₺)'),
        ),
    ]
