# Generated by Django 4.2.30 on 2026-04-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiraci', '0003_kiraci_depozit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiraci',
            name='kira_gunu',
            field=models.IntegerField(default=1, verbose_name='Kira Ödeme Günü (ayın kaçı)'),
        ),
        migrations.AddField(
            model_name='kiraci',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp No (5XXXXXXXXX)'),
        ),
        migrations.CreateModel(
            name='BildirimLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField()),
                ('ay', models.IntegerField()),
                ('gonderildi_at', models.DateTimeField(auto_now_add=True)),
                ('mesaj', models.TextField(blank=True)),
                ('kiraci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to='kiraci.kiraci')),
            ],
            options={
                'verbose_name': 'Bildirim Logu',
                'verbose_name_plural': 'Bildirim Logları',
                'ordering': ['-gonderildi_at'],
            },
        ),
    ]
