# Generated by Django 4.2.30 on 2026-04-10 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiraci', '0004_kiraci_kira_gunu_kiraci_whatsapp_no_bildirimlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiraci',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kiraciler', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callmebot_api_key', models.CharField(blank=True, max_length=50, verbose_name='CallMeBot API Key')),
                ('whatsapp_no', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp No (5XXXXXXXXX)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
            },
        ),
    ]
