# Generated by Django 4.2.30 on 2026-04-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiraci', '0005_kiraci_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bildirim_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Bildirim Email Adresi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_bildirimleri',
            field=models.BooleanField(default=False, verbose_name='Email Bildirimleri'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=100, verbose_name='SMTP Sunucu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='SMTP Şifre / App Password'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_port',
            field=models.IntegerField(default=587, verbose_name='SMTP Port'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smtp_user',
            field=models.EmailField(blank=True, max_length=254, verbose_name='SMTP Kullanıcı (Gmail)'),
        ),
    ]
