# Generated by Django 4.2.30 on 2026-04-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiraci', '0006_userprofile_bildirim_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirimlog',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bildirimlog',
            name='yanitlandi',
            field=models.BooleanField(default=False),
        ),
    ]
