# Generated by Django 4.2.30 on 2026-06-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiraci', '0007_bildirimlog_token_bildirimlog_yanitlandi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odeme',
            name='odeme_turu',
            field=models.CharField(choices=[('nakit', 'Nakit')], max_length=20, verbose_name='Ödeme Türü'),
        ),
    ]
