# Generated by Django 4.2.30 on 2026-06-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiraci', '0008_alter_odeme_odeme_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiraci',
            name='yillik_kira_tutari',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Yıllık Kira Tutarı (₺)'),
        ),
    ]
