# Generated by Django 4.2.30 on 2026-06-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiraci', '0009_kiraci_yillik_kira_tutari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiraci',
            name='aylik_kira_tutari',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Aylık Kira Tutarı (₺)'),
        ),
    ]
